// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (clinic_id, doctor_id, patient_id, room_id, appointment_type_id, start_time, end_time, notes, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, clinic_id, doctor_id, patient_id, start_time, end_time, status, created_at
`

type CreateAppointmentParams struct {
	ClinicID          int64              `json:"clinic_id"`
	DoctorID          int64              `json:"doctor_id"`
	PatientID         int64              `json:"patient_id"`
	RoomID            pgtype.Int8        `json:"room_id"`
	AppointmentTypeID pgtype.Int8        `json:"appointment_type_id"`
	StartTime         pgtype.Timestamptz `json:"start_time"`
	EndTime           pgtype.Timestamptz `json:"end_time"`
	Notes             pgtype.Text        `json:"notes"`
	Status            pgtype.Text        `json:"status"`
}

type CreateAppointmentRow struct {
	ID        int64              `json:"id"`
	ClinicID  int64              `json:"clinic_id"`
	DoctorID  int64              `json:"doctor_id"`
	PatientID int64              `json:"patient_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
	Status    pgtype.Text        `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (CreateAppointmentRow, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.ClinicID,
		arg.DoctorID,
		arg.PatientID,
		arg.RoomID,
		arg.AppointmentTypeID,
		arg.StartTime,
		arg.EndTime,
		arg.Notes,
		arg.Status,
	)
	var i CreateAppointmentRow
	err := row.Scan(
		&i.ID,
		&i.ClinicID,
		&i.DoctorID,
		&i.PatientID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listAppointmentsByRange = `-- name: ListAppointmentsByRange :many
SELECT a.id, a.clinic_id, a.doctor_id, a.patient_id, a.room_id, a.appointment_type_id, a.start_time, a.end_time, a.status, a.notes,
       p.full_name as patient_name, u.name as doctor_name
FROM appointments a
JOIN patients p ON a.patient_id = p.id
JOIN users u ON a.doctor_id = u.id
WHERE a.clinic_id = $1 AND a.start_time >= $2 AND a.end_time <= $3 AND a.deleted_at IS NULL
ORDER BY a.start_time ASC
`

type ListAppointmentsByRangeParams struct {
	ClinicID  int64              `json:"clinic_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

type ListAppointmentsByRangeRow struct {
	ID                int64              `json:"id"`
	ClinicID          int64              `json:"clinic_id"`
	DoctorID          int64              `json:"doctor_id"`
	PatientID         int64              `json:"patient_id"`
	RoomID            pgtype.Int8        `json:"room_id"`
	AppointmentTypeID pgtype.Int8        `json:"appointment_type_id"`
	StartTime         pgtype.Timestamptz `json:"start_time"`
	EndTime           pgtype.Timestamptz `json:"end_time"`
	Status            pgtype.Text        `json:"status"`
	Notes             pgtype.Text        `json:"notes"`
	PatientName       string             `json:"patient_name"`
	DoctorName        string             `json:"doctor_name"`
}

func (q *Queries) ListAppointmentsByRange(ctx context.Context, arg ListAppointmentsByRangeParams) ([]ListAppointmentsByRangeRow, error) {
	rows, err := q.db.Query(ctx, listAppointmentsByRange, arg.ClinicID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppointmentsByRangeRow
	for rows.Next() {
		var i ListAppointmentsByRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.ClinicID,
			&i.DoctorID,
			&i.PatientID,
			&i.RoomID,
			&i.AppointmentTypeID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.Notes,
			&i.PatientName,
			&i.DoctorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppointmentStatus = `-- name: UpdateAppointmentStatus :exec
UPDATE appointments
SET status = $1, updated_at = NOW()
WHERE id = $2 AND clinic_id = $3
`

type UpdateAppointmentStatusParams struct {
	Status   pgtype.Text `json:"status"`
	ID       int64       `json:"id"`
	ClinicID int64       `json:"clinic_id"`
}

func (q *Queries) UpdateAppointmentStatus(ctx context.Context, arg UpdateAppointmentStatusParams) error {
	_, err := q.db.Exec(ctx, updateAppointmentStatus, arg.Status, arg.ID, arg.ClinicID)
	return err
}
