// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clinics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClinic = `-- name: CreateClinic :one
INSERT INTO clinics (name, cnpj, email, phone, status, plan, trial_ends_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, cnpj, email, phone, status, plan, trial_ends_at, created_at
`

type CreateClinicParams struct {
	Name        string             `json:"name"`
	Cnpj        string             `json:"cnpj"`
	Email       pgtype.Text        `json:"email"`
	Phone       pgtype.Text        `json:"phone"`
	Status      pgtype.Text        `json:"status"`
	Plan        pgtype.Text        `json:"plan"`
	TrialEndsAt pgtype.Timestamptz `json:"trial_ends_at"`
}

type CreateClinicRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Cnpj        string             `json:"cnpj"`
	Email       pgtype.Text        `json:"email"`
	Phone       pgtype.Text        `json:"phone"`
	Status      pgtype.Text        `json:"status"`
	Plan        pgtype.Text        `json:"plan"`
	TrialEndsAt pgtype.Timestamptz `json:"trial_ends_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateClinic(ctx context.Context, arg CreateClinicParams) (CreateClinicRow, error) {
	row := q.db.QueryRow(ctx, createClinic,
		arg.Name,
		arg.Cnpj,
		arg.Email,
		arg.Phone,
		arg.Status,
		arg.Plan,
		arg.TrialEndsAt,
	)
	var i CreateClinicRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cnpj,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.Plan,
		&i.TrialEndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const getClinicByID = `-- name: GetClinicByID :one
SELECT id, name, cnpj, email, phone, status, plan, trial_ends_at, created_at, updated_at
FROM clinics
WHERE id = $1 AND deleted_at IS NULL
`

type GetClinicByIDRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Cnpj        string             `json:"cnpj"`
	Email       pgtype.Text        `json:"email"`
	Phone       pgtype.Text        `json:"phone"`
	Status      pgtype.Text        `json:"status"`
	Plan        pgtype.Text        `json:"plan"`
	TrialEndsAt pgtype.Timestamptz `json:"trial_ends_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetClinicByID(ctx context.Context, id int64) (GetClinicByIDRow, error) {
	row := q.db.QueryRow(ctx, getClinicByID, id)
	var i GetClinicByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cnpj,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.Plan,
		&i.TrialEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateClinicStatus = `-- name: UpdateClinicStatus :exec
UPDATE clinics
SET status = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateClinicStatusParams struct {
	Status pgtype.Text `json:"status"`
	ID     int64       `json:"id"`
}

func (q *Queries) UpdateClinicStatus(ctx context.Context, arg UpdateClinicStatusParams) error {
	_, err := q.db.Exec(ctx, updateClinicStatus, arg.Status, arg.ID)
	return err
}
