// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: financial.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO clinic_transactions (clinic_id, patient_id, budget_id, type, category, description, amount, payment_method, due_date, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, clinic_id, type, category, amount, status, created_at
`

type CreateTransactionParams struct {
	ClinicID      int64          `json:"clinic_id"`
	PatientID     pgtype.Int8    `json:"patient_id"`
	BudgetID      pgtype.Int8    `json:"budget_id"`
	Type          string         `json:"type"`
	Category      string         `json:"category"`
	Description   string         `json:"description"`
	Amount        pgtype.Numeric `json:"amount"`
	PaymentMethod pgtype.Text    `json:"payment_method"`
	DueDate       pgtype.Date    `json:"due_date"`
	Status        string         `json:"status"`
}

type CreateTransactionRow struct {
	ID        int64              `json:"id"`
	ClinicID  int64              `json:"clinic_id"`
	Type      string             `json:"type"`
	Category  string             `json:"category"`
	Amount    pgtype.Numeric     `json:"amount"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.ClinicID,
		arg.PatientID,
		arg.BudgetID,
		arg.Type,
		arg.Category,
		arg.Description,
		arg.Amount,
		arg.PaymentMethod,
		arg.DueDate,
		arg.Status,
	)
	var i CreateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.ClinicID,
		&i.Type,
		&i.Category,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactionsByClinic = `-- name: ListTransactionsByClinic :many
SELECT id, clinic_id, patient_id, budget_id, type, category, description, amount, payment_method, due_date, payment_date, status, created_at
FROM clinic_transactions
WHERE clinic_id = $1 AND deleted_at IS NULL
ORDER BY due_date DESC
`

type ListTransactionsByClinicRow struct {
	ID            int64              `json:"id"`
	ClinicID      int64              `json:"clinic_id"`
	PatientID     pgtype.Int8        `json:"patient_id"`
	BudgetID      pgtype.Int8        `json:"budget_id"`
	Type          string             `json:"type"`
	Category      string             `json:"category"`
	Description   string             `json:"description"`
	Amount        pgtype.Numeric     `json:"amount"`
	PaymentMethod pgtype.Text        `json:"payment_method"`
	DueDate       pgtype.Date        `json:"due_date"`
	PaymentDate   pgtype.Date        `json:"payment_date"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListTransactionsByClinic(ctx context.Context, clinicID int64) ([]ListTransactionsByClinicRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByClinic, clinicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsByClinicRow
	for rows.Next() {
		var i ListTransactionsByClinicRow
		if err := rows.Scan(
			&i.ID,
			&i.ClinicID,
			&i.PatientID,
			&i.BudgetID,
			&i.Type,
			&i.Category,
			&i.Description,
			&i.Amount,
			&i.PaymentMethod,
			&i.DueDate,
			&i.PaymentDate,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
