// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Appointment struct {
	ID                int64              `json:"id"`
	ClinicID          int64              `json:"clinic_id"`
	DoctorID          int64              `json:"doctor_id"`
	PatientID         int64              `json:"patient_id"`
	RoomID            pgtype.Int8        `json:"room_id"`
	AppointmentTypeID pgtype.Int8        `json:"appointment_type_id"`
	StartTime         pgtype.Timestamptz `json:"start_time"`
	EndTime           pgtype.Timestamptz `json:"end_time"`
	ActualStartTime   pgtype.Timestamptz `json:"actual_start_time"`
	ActualEndTime     pgtype.Timestamptz `json:"actual_end_time"`
	Notes             pgtype.Text        `json:"notes"`
	Status            pgtype.Text        `json:"status"`
	DeletedBy         pgtype.Int8        `json:"deleted_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type AppointmentType struct {
	ID        int64              `json:"id"`
	ClinicID  int64              `json:"clinic_id"`
	Name      string             `json:"name"`
	Color     pgtype.Text        `json:"color"`
	Duration  pgtype.Int4        `json:"duration"`
	Price     pgtype.Numeric     `json:"price"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type AuditLog struct {
	ID        int64              `json:"id"`
	ClinicID  int64              `json:"clinic_id"`
	UserID    pgtype.Int8        `json:"user_id"`
	Action    string             `json:"action"`
	Entity    string             `json:"entity"`
	EntityID  pgtype.Int8        `json:"entity_id"`
	IpAddress pgtype.Text        `json:"ip_address"`
	UserAgent pgtype.Text        `json:"user_agent"`
	Details   pgtype.Text        `json:"details"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Budget struct {
	ID             int64              `json:"id"`
	ClinicID       int64              `json:"clinic_id"`
	PatientID      int64              `json:"patient_id"`
	DoctorID       pgtype.Int8        `json:"doctor_id"`
	TotalAmount    pgtype.Numeric     `json:"total_amount"`
	DiscountAmount pgtype.Numeric     `json:"discount_amount"`
	FinalAmount    pgtype.Numeric     `json:"final_amount"`
	Status         pgtype.Text        `json:"status"`
	ValidUntil     pgtype.Timestamptz `json:"valid_until"`
	Notes          pgtype.Text        `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type BudgetItem struct {
	ID          int64              `json:"id"`
	BudgetID    int64              `json:"budget_id"`
	ProcedureID pgtype.Int8        `json:"procedure_id"`
	ToothNumber pgtype.Int4        `json:"tooth_number"`
	Surface     pgtype.Text        `json:"surface"`
	UnitPrice   pgtype.Numeric     `json:"unit_price"`
	Quantity    pgtype.Int4        `json:"quantity"`
	TotalPrice  pgtype.Numeric     `json:"total_price"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Clinic struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Cnpj        string             `json:"cnpj"`
	Email       pgtype.Text        `json:"email"`
	Phone       pgtype.Text        `json:"phone"`
	Status      pgtype.Text        `json:"status"`
	Plan        pgtype.Text        `json:"plan"`
	TrialEndsAt pgtype.Timestamptz `json:"trial_ends_at"`
	DeletedBy   pgtype.Int8        `json:"deleted_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type ClinicTransaction struct {
	ID            int64              `json:"id"`
	ClinicID      int64              `json:"clinic_id"`
	PatientID     pgtype.Int8        `json:"patient_id"`
	BudgetID      pgtype.Int8        `json:"budget_id"`
	Type          string             `json:"type"`
	Category      string             `json:"category"`
	Description   string             `json:"description"`
	Amount        pgtype.Numeric     `json:"amount"`
	PaymentMethod pgtype.Text        `json:"payment_method"`
	DueDate       pgtype.Date        `json:"due_date"`
	PaymentDate   pgtype.Date        `json:"payment_date"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type ClinicalEvolution struct {
	ID            int64              `json:"id"`
	ClinicID      int64              `json:"clinic_id"`
	PatientID     int64              `json:"patient_id"`
	DoctorID      int64              `json:"doctor_id"`
	AppointmentID pgtype.Int8        `json:"appointment_id"`
	Description   string             `json:"description"`
	QuillDelta    pgtype.Text        `json:"quill_delta"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type ClinicalNote struct {
	ID        int64              `json:"id"`
	ClinicID  int64              `json:"clinic_id"`
	PatientID int64              `json:"patient_id"`
	DoctorID  int64              `json:"doctor_id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	Category  pgtype.Text        `json:"category"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type MedicalDocument struct {
	ID        int64              `json:"id"`
	ClinicID  int64              `json:"clinic_id"`
	PatientID int64              `json:"patient_id"`
	DoctorID  int64              `json:"doctor_id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	FilePath  pgtype.Text        `json:"file_path"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Patient struct {
	ID              int64              `json:"id"`
	ClinicID        int64              `json:"clinic_id"`
	FullName        string             `json:"full_name"`
	CpfEncrypted    string             `json:"cpf_encrypted"`
	Email           pgtype.Text        `json:"email"`
	PhoneEncrypted  string             `json:"phone_encrypted"`
	Cep             pgtype.Text        `json:"cep"`
	Street          pgtype.Text        `json:"street"`
	Neighborhood    pgtype.Text        `json:"neighborhood"`
	Number          pgtype.Text        `json:"number"`
	HealthInsurance pgtype.Text        `json:"health_insurance"`
	BirthDate       pgtype.Date        `json:"birth_date"`
	MedicalHistory  pgtype.Text        `json:"medical_history"`
	NotesEncrypted  pgtype.Text        `json:"notes_encrypted"`
	Weight          pgtype.Numeric     `json:"weight"`
	DeletedBy       pgtype.Int8        `json:"deleted_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type Procedure struct {
	ID        int64              `json:"id"`
	ClinicID  int64              `json:"clinic_id"`
	Code      pgtype.Text        `json:"code"`
	Name      string             `json:"name"`
	Category  pgtype.Text        `json:"category"`
	BaseCost  pgtype.Numeric     `json:"base_cost"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Role struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Permissions pgtype.Text        `json:"permissions"`
	ClinicID    pgtype.Int8        `json:"clinic_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Room struct {
	ID          int64              `json:"id"`
	ClinicID    int64              `json:"clinic_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Status      pgtype.Text        `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type TeethStatus struct {
	ID          int64              `json:"id"`
	ClinicID    int64              `json:"clinic_id"`
	PatientID   int64              `json:"patient_id"`
	ToothNumber int32              `json:"tooth_number"`
	Condition   string             `json:"condition"`
	Surface     pgtype.Text        `json:"surface"`
	Notes       pgtype.Text        `json:"notes"`
	UpdatedBy   pgtype.Int8        `json:"updated_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID              int64              `json:"id"`
	ClinicID        int64              `json:"clinic_id"`
	RoleID          pgtype.Int8        `json:"role_id"`
	CurrentRoomID   pgtype.Int8        `json:"current_room_id"`
	Name            string             `json:"name"`
	Email           string             `json:"email"`
	Password        string             `json:"password"`
	Cpf             pgtype.Text        `json:"cpf"`
	Phone           pgtype.Text        `json:"phone"`
	Address         pgtype.Text        `json:"address"`
	MedicalRegistry pgtype.Text        `json:"medical_registry"`
	Ctps            pgtype.Text        `json:"ctps"`
	Avatar          pgtype.Text        `json:"avatar"`
	ThemePreference pgtype.Text        `json:"theme_preference"`
	FailedAttempts  pgtype.Int4        `json:"failed_attempts"`
	LockedUntil     pgtype.Timestamptz `json:"locked_until"`
	DeletedBy       pgtype.Int8        `json:"deleted_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}
