// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patients.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPatient = `-- name: CreatePatient :one
INSERT INTO patients (clinic_id, full_name, cpf_encrypted, email, phone_encrypted, cep, street, neighborhood, number, health_insurance, birth_date, medical_history, notes_encrypted, weight)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, clinic_id, full_name, cpf_encrypted, email, phone_encrypted, created_at
`

type CreatePatientParams struct {
	ClinicID        int64          `json:"clinic_id"`
	FullName        string         `json:"full_name"`
	CpfEncrypted    string         `json:"cpf_encrypted"`
	Email           pgtype.Text    `json:"email"`
	PhoneEncrypted  string         `json:"phone_encrypted"`
	Cep             pgtype.Text    `json:"cep"`
	Street          pgtype.Text    `json:"street"`
	Neighborhood    pgtype.Text    `json:"neighborhood"`
	Number          pgtype.Text    `json:"number"`
	HealthInsurance pgtype.Text    `json:"health_insurance"`
	BirthDate       pgtype.Date    `json:"birth_date"`
	MedicalHistory  pgtype.Text    `json:"medical_history"`
	NotesEncrypted  pgtype.Text    `json:"notes_encrypted"`
	Weight          pgtype.Numeric `json:"weight"`
}

type CreatePatientRow struct {
	ID             int64              `json:"id"`
	ClinicID       int64              `json:"clinic_id"`
	FullName       string             `json:"full_name"`
	CpfEncrypted   string             `json:"cpf_encrypted"`
	Email          pgtype.Text        `json:"email"`
	PhoneEncrypted string             `json:"phone_encrypted"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (CreatePatientRow, error) {
	row := q.db.QueryRow(ctx, createPatient,
		arg.ClinicID,
		arg.FullName,
		arg.CpfEncrypted,
		arg.Email,
		arg.PhoneEncrypted,
		arg.Cep,
		arg.Street,
		arg.Neighborhood,
		arg.Number,
		arg.HealthInsurance,
		arg.BirthDate,
		arg.MedicalHistory,
		arg.NotesEncrypted,
		arg.Weight,
	)
	var i CreatePatientRow
	err := row.Scan(
		&i.ID,
		&i.ClinicID,
		&i.FullName,
		&i.CpfEncrypted,
		&i.Email,
		&i.PhoneEncrypted,
		&i.CreatedAt,
	)
	return i, err
}

const getPatientByID = `-- name: GetPatientByID :one
SELECT id, clinic_id, full_name, cpf_encrypted, email, phone_encrypted, cep, street, neighborhood, number, health_insurance, birth_date, medical_history, notes_encrypted, weight, created_at, updated_at
FROM patients
WHERE id = $1 AND clinic_id = $2 AND deleted_at IS NULL
`

type GetPatientByIDParams struct {
	ID       int64 `json:"id"`
	ClinicID int64 `json:"clinic_id"`
}

type GetPatientByIDRow struct {
	ID              int64              `json:"id"`
	ClinicID        int64              `json:"clinic_id"`
	FullName        string             `json:"full_name"`
	CpfEncrypted    string             `json:"cpf_encrypted"`
	Email           pgtype.Text        `json:"email"`
	PhoneEncrypted  string             `json:"phone_encrypted"`
	Cep             pgtype.Text        `json:"cep"`
	Street          pgtype.Text        `json:"street"`
	Neighborhood    pgtype.Text        `json:"neighborhood"`
	Number          pgtype.Text        `json:"number"`
	HealthInsurance pgtype.Text        `json:"health_insurance"`
	BirthDate       pgtype.Date        `json:"birth_date"`
	MedicalHistory  pgtype.Text        `json:"medical_history"`
	NotesEncrypted  pgtype.Text        `json:"notes_encrypted"`
	Weight          pgtype.Numeric     `json:"weight"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPatientByID(ctx context.Context, arg GetPatientByIDParams) (GetPatientByIDRow, error) {
	row := q.db.QueryRow(ctx, getPatientByID, arg.ID, arg.ClinicID)
	var i GetPatientByIDRow
	err := row.Scan(
		&i.ID,
		&i.ClinicID,
		&i.FullName,
		&i.CpfEncrypted,
		&i.Email,
		&i.PhoneEncrypted,
		&i.Cep,
		&i.Street,
		&i.Neighborhood,
		&i.Number,
		&i.HealthInsurance,
		&i.BirthDate,
		&i.MedicalHistory,
		&i.NotesEncrypted,
		&i.Weight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPatientsByClinic = `-- name: ListPatientsByClinic :many
SELECT id, clinic_id, full_name, cpf_encrypted, email, phone_encrypted, birth_date, health_insurance, created_at
FROM patients
WHERE clinic_id = $1 AND deleted_at IS NULL
ORDER BY full_name ASC
LIMIT $2 OFFSET $3
`

type ListPatientsByClinicParams struct {
	ClinicID int64 `json:"clinic_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

type ListPatientsByClinicRow struct {
	ID              int64              `json:"id"`
	ClinicID        int64              `json:"clinic_id"`
	FullName        string             `json:"full_name"`
	CpfEncrypted    string             `json:"cpf_encrypted"`
	Email           pgtype.Text        `json:"email"`
	PhoneEncrypted  string             `json:"phone_encrypted"`
	BirthDate       pgtype.Date        `json:"birth_date"`
	HealthInsurance pgtype.Text        `json:"health_insurance"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPatientsByClinic(ctx context.Context, arg ListPatientsByClinicParams) ([]ListPatientsByClinicRow, error) {
	rows, err := q.db.Query(ctx, listPatientsByClinic, arg.ClinicID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatientsByClinicRow
	for rows.Next() {
		var i ListPatientsByClinicRow
		if err := rows.Scan(
			&i.ID,
			&i.ClinicID,
			&i.FullName,
			&i.CpfEncrypted,
			&i.Email,
			&i.PhoneEncrypted,
			&i.BirthDate,
			&i.HealthInsurance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePatient = `-- name: SoftDeletePatient :exec
UPDATE patients
SET deleted_at = NOW(), deleted_by = $3
WHERE id = $1 AND clinic_id = $2
`

type SoftDeletePatientParams struct {
	ID        int64       `json:"id"`
	ClinicID  int64       `json:"clinic_id"`
	DeletedBy pgtype.Int8 `json:"deleted_by"`
}

func (q *Queries) SoftDeletePatient(ctx context.Context, arg SoftDeletePatientParams) error {
	_, err := q.db.Exec(ctx, softDeletePatient, arg.ID, arg.ClinicID, arg.DeletedBy)
	return err
}
