// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (clinic_id, role_id, name, email, password, cpf, phone, avatar)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, clinic_id, role_id, name, email, password, created_at, updated_at
`

type CreateUserParams struct {
	ClinicID int64       `json:"clinic_id"`
	RoleID   pgtype.Int8 `json:"role_id"`
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	Password string      `json:"password"`
	Cpf      pgtype.Text `json:"cpf"`
	Phone    pgtype.Text `json:"phone"`
	Avatar   pgtype.Text `json:"avatar"`
}

type CreateUserRow struct {
	ID        int64              `json:"id"`
	ClinicID  int64              `json:"clinic_id"`
	RoleID    pgtype.Int8        `json:"role_id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ClinicID,
		arg.RoleID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Cpf,
		arg.Phone,
		arg.Avatar,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.ClinicID,
		&i.RoleID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, clinic_id, role_id, name, email, password, cpf, phone, avatar, theme_preference, failed_attempts, locked_until, created_at, updated_at
FROM users
WHERE email = $1 AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID              int64              `json:"id"`
	ClinicID        int64              `json:"clinic_id"`
	RoleID          pgtype.Int8        `json:"role_id"`
	Name            string             `json:"name"`
	Email           string             `json:"email"`
	Password        string             `json:"password"`
	Cpf             pgtype.Text        `json:"cpf"`
	Phone           pgtype.Text        `json:"phone"`
	Avatar          pgtype.Text        `json:"avatar"`
	ThemePreference pgtype.Text        `json:"theme_preference"`
	FailedAttempts  pgtype.Int4        `json:"failed_attempts"`
	LockedUntil     pgtype.Timestamptz `json:"locked_until"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.ClinicID,
		&i.RoleID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Cpf,
		&i.Phone,
		&i.Avatar,
		&i.ThemePreference,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, clinic_id, role_id, name, email, password, cpf, phone, avatar, theme_preference, failed_attempts, locked_until, created_at, updated_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID              int64              `json:"id"`
	ClinicID        int64              `json:"clinic_id"`
	RoleID          pgtype.Int8        `json:"role_id"`
	Name            string             `json:"name"`
	Email           string             `json:"email"`
	Password        string             `json:"password"`
	Cpf             pgtype.Text        `json:"cpf"`
	Phone           pgtype.Text        `json:"phone"`
	Avatar          pgtype.Text        `json:"avatar"`
	ThemePreference pgtype.Text        `json:"theme_preference"`
	FailedAttempts  pgtype.Int4        `json:"failed_attempts"`
	LockedUntil     pgtype.Timestamptz `json:"locked_until"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.ClinicID,
		&i.RoleID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Cpf,
		&i.Phone,
		&i.Avatar,
		&i.ThemePreference,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserFailedAttempts = `-- name: UpdateUserFailedAttempts :exec
UPDATE users
SET failed_attempts = $1, locked_until = $2, updated_at = NOW()
WHERE id = $3
`

type UpdateUserFailedAttemptsParams struct {
	FailedAttempts pgtype.Int4        `json:"failed_attempts"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
	ID             int64              `json:"id"`
}

func (q *Queries) UpdateUserFailedAttempts(ctx context.Context, arg UpdateUserFailedAttemptsParams) error {
	_, err := q.db.Exec(ctx, updateUserFailedAttempts, arg.FailedAttempts, arg.LockedUntil, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateUserPasswordParams struct {
	Password string `json:"password"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.Password, arg.ID)
	return err
}
