-- Migration: 20260904000001_initial_schema.sql
-- Description: Criação do esquema completo de tabelas compatível com os modelos Go GORM (BIGINT uint)

-- 1. Clínicas
CREATE TABLE IF NOT EXISTS public.clinics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    cnpj VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(255),
    phone VARCHAR(20),
    status VARCHAR(50) DEFAULT 'active',
    plan VARCHAR(50) DEFAULT 'premium',
    trial_ends_at TIMESTAMPTZ,
    deleted_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- 2. Cargos e Permissões (Roles)
CREATE TABLE IF NOT EXISTS public.roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    permissions TEXT DEFAULT '[]',
    clinic_id BIGINT REFERENCES public.clinics(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Usuários / Profissionais
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id BIGINT NOT NULL REFERENCES public.clinics(id) ON DELETE CASCADE,
    role_id BIGINT REFERENCES public.roles(id) ON DELETE SET NULL,
    current_room_id BIGINT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    cpf VARCHAR(20),
    phone VARCHAR(20),
    address TEXT,
    medical_registry VARCHAR(50),
    ctps VARCHAR(50),
    avatar VARCHAR(255),
    theme_preference VARCHAR(20) DEFAULT 'system',
    failed_attempts INT DEFAULT 0,
    locked_until TIMESTAMPTZ,
    deleted_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- 4. Salas Cirúrgicas / Consultórios
CREATE TABLE IF NOT EXISTS public.rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id BIGINT NOT NULL REFERENCES public.clinics(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    status VARCHAR(20) DEFAULT 'available',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- 5. Pacientes
CREATE TABLE IF NOT EXISTS public.patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id BIGINT NOT NULL REFERENCES public.clinics(id) ON DELETE CASCADE,
    full_name VARCHAR(150) NOT NULL,
    cpf_encrypted TEXT NOT NULL,
    email VARCHAR(150),
    phone_encrypted TEXT NOT NULL,
    cep VARCHAR(20),
    street VARCHAR(255),
    neighborhood VARCHAR(255),
    number VARCHAR(50),
    health_insurance VARCHAR(100),
    birth_date DATE,
    medical_history TEXT,
    notes_encrypted TEXT,
    weight NUMERIC(5, 2),
    deleted_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- 6. Tipos de Consulta / Atendimento
CREATE TABLE IF NOT EXISTS public.appointment_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id BIGINT NOT NULL REFERENCES public.clinics(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    color VARCHAR(20) DEFAULT '#2563EB',
    duration INT DEFAULT 30,
    price NUMERIC(10, 2) DEFAULT 0.00,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- 7. Agendamentos
CREATE TABLE IF NOT EXISTS public.appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id BIGINT NOT NULL REFERENCES public.clinics(id) ON DELETE CASCADE,
    doctor_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    patient_id BIGINT NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
    room_id BIGINT REFERENCES public.rooms(id) ON DELETE SET NULL,
    appointment_type_id BIGINT REFERENCES public.appointment_types(id) ON DELETE SET NULL,
    start_time TIMESTAMPTZ,
    end_time TIMESTAMPTZ,
    actual_start_time TIMESTAMPTZ,
    actual_end_time TIMESTAMPTZ,
    notes TEXT,
    status VARCHAR(50) DEFAULT 'scheduled',
    deleted_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- 8. Procedimentos Médicos e Tabela de Preços
CREATE TABLE IF NOT EXISTS public.procedures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id BIGINT NOT NULL REFERENCES public.clinics(id) ON DELETE CASCADE,
    code VARCHAR(50),
    name VARCHAR(150) NOT NULL,
    category VARCHAR(100),
    base_cost NUMERIC(10, 2) DEFAULT 0.00,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- 9. Orçamentos (Budgets) e Itens
CREATE TABLE IF NOT EXISTS public.budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id BIGINT NOT NULL REFERENCES public.clinics(id) ON DELETE CASCADE,
    patient_id BIGINT NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
    doctor_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    total_amount NUMERIC(10, 2) DEFAULT 0.00,
    discount_amount NUMERIC(10, 2) DEFAULT 0.00,
    final_amount NUMERIC(10, 2) DEFAULT 0.00,
    status VARCHAR(50) DEFAULT 'draft',
    valid_until TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.budget_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_id BIGINT NOT NULL REFERENCES public.budgets(id) ON DELETE CASCADE,
    procedure_id BIGINT REFERENCES public.procedures(id) ON DELETE SET NULL,
    tooth_number INT,
    surface VARCHAR(50),
    unit_price NUMERIC(10, 2) DEFAULT 0.00,
    quantity INT DEFAULT 1,
    total_price NUMERIC(10, 2) DEFAULT 0.00,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 10. Evolução Clínica e Anotações
CREATE TABLE IF NOT EXISTS public.clinical_evolutions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id BIGINT NOT NULL REFERENCES public.clinics(id) ON DELETE CASCADE,
    patient_id BIGINT NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
    doctor_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    appointment_id BIGINT REFERENCES public.appointments(id) ON DELETE SET NULL,
    description TEXT NOT NULL,
    quill_delta TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.clinical_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id BIGINT NOT NULL REFERENCES public.clinics(id) ON DELETE CASCADE,
    patient_id BIGINT NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
    doctor_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    category VARCHAR(50) DEFAULT 'general',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- 11. Documentos Médicos / Receituários / Atestados
CREATE TABLE IF NOT EXISTS public.medical_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id BIGINT NOT NULL REFERENCES public.clinics(id) ON DELETE CASCADE,
    patient_id BIGINT NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
    doctor_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    file_path VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- 12. Odontograma (Teeth Status & History)
CREATE TABLE IF NOT EXISTS public.teeth_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id BIGINT NOT NULL REFERENCES public.clinics(id) ON DELETE CASCADE,
    patient_id BIGINT NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
    tooth_number INT NOT NULL,
    condition VARCHAR(50) NOT NULL,
    surface VARCHAR(50),
    notes TEXT,
    updated_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 13. Transações Financeiras e Parcelas
CREATE TABLE IF NOT EXISTS public.clinic_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id BIGINT NOT NULL REFERENCES public.clinics(id) ON DELETE CASCADE,
    patient_id BIGINT REFERENCES public.patients(id) ON DELETE SET NULL,
    budget_id BIGINT REFERENCES public.budgets(id) ON DELETE SET NULL,
    type VARCHAR(20) NOT NULL CHECK (type IN ('income', 'expense')),
    category VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    payment_method VARCHAR(50),
    due_date DATE NOT NULL,
    payment_date DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- 14. Logs de Auditoria (LGPD)
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id BIGINT NOT NULL REFERENCES public.clinics(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    action VARCHAR(100) NOT NULL,
    entity VARCHAR(100) NOT NULL,
    entity_id BIGINT,
    ip_address VARCHAR(50),
    user_agent TEXT,
    details TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
